# Generated by Django 3.1.7 on 2021-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date_Example ===== 2021-04-02 11:36:16  '),
        ),
    ]
