# Generated by Django 3.1.7 on 2021-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210403_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(max_length=200, verbose_name='Information_name')),
                ('information_text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
