# Generated by Django 3.1.7 on 2021-04-08 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210408_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 37, 38, 669925, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
