# Generated by Django 3.1.7 on 2021-04-08 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 17, 34, 25, 780491, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
