# Generated by Django 3.1.7 on 2021-04-08 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210408_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 17, 58, 4, 197229, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
