# Generated by Django 3.1.7 on 2021-04-09 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210409_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 12, 56, 20, 450658, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
