# Generated by Django 3.1.7 on 2021-04-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210409_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
