# Generated by Django 3.1.7 on 2021-04-13 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_image_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографіі класу'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Інфо', 'verbose_name_plural': 'Інформація для учнів'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 7, 15, 16, 713133, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
