# Generated by Django 3.1.7 on 2021-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20210413_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Image', max_length=50),
        ),
    ]
