# Generated by Django 3.1.7 on 2021-04-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20210413_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Наші досягнення',
            },
        ),
    ]
